import type { Metadata } from "next";
import { Doto, Raleway } from "next/font/google";
import "./globals.css";


const doto = Doto({
  variable: "--font-doto",
  subsets: ["latin"]
})

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${doto.variable} ${raleway.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
